FROM nginx:1.23-alpine
COPY referencedata.d/ /usr/share/nginx/html/referencedata.d/
COPY samples.d/ /usr/share/nginx/html/samples.d/
COPY implementation-detail-data.d/ /usr/share/nginx/html/implementation-detail-data.d/
